version: '3.8'

services:
  studio-ai:
    build: .
    container_name: studio-ai-app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - HOST=0.0.0.0
      - PORT=8000
    env_file:
      - .env
    volumes:
      # Mount generated images directory for persistence
      - ./static/generated_images:/app/static/generated_images
      # Mount credentials if using Google Cloud
      - ./credentials:/app/credentials:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - studio-ai-network

  # Optional: Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: studio-ai-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl:ro
    depends_on:
      - studio-ai
    restart: unless-stopped
    networks:
      - studio-ai-network
    profiles:
      - production

networks:
  studio-ai-network:
    driver: bridge

volumes:
  generated_images:
    driver: local